### ISSUE TITLE
Encountering "KeyError: 'text'" in the Kosmos2 finetuning notebook both in collab and local.

### ISSUE THREAD

**Issue by beingdutta** [mit1280/fined-tuning#3]
I tried to run the Kosmos2 finetuning notebook on the poekmon dataset, but faced few of the warnings, I believe for the version number has been changed.

But on running the 

```
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset.select(range(300)),
    eval_dataset=dataset.select(range(10)),
    peft_config=lora_config,
    tokenizer=processor.tokenizer,
    data_collator=data_collator,
)

trainer.train()
```

Im encountering this error both in my local env and in collab.

File ~/miniconda3/envs/stable_env/lib/python3.9/site-packages/datasets/arrow_dataset.py:3338, in Dataset._map_single.<locals>.apply_function_on_filtered_inputs(pa_inputs, indices, check_same_num_examples, offset)
   3336 if with_rank:
   3337     additional_args += (rank,)
-> 3338 processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
   3339 if isinstance(processed_inputs, LazyDict):
   3340     processed_inputs = {
   3341         k: v for k, v in processed_inputs.data.items() if k not in processed_inputs.keys_to_format
   3342     }

File ~/miniconda3/envs/stable_env/lib/python3.9/site-packages/trl/trainer/sft_trainer.py:513, in SFTTrainer._prepare_non_packed_dataloader.<locals>.tokenize(element)
    511 def tokenize(element):
    512     outputs = processing_class(
--> 513         element[dataset_text_field] if formatting_func is None else formatting_func(element),
    514         add_special_tokens=add_special_tokens,
    515         truncation=True,
    516         padding=False,
    517         max_length=max_seq_length,
    518         return_overflowing_tokens=False,
    519         return_length=False,
    520     )
    522     if formatting_func is not None and not isinstance(formatting_func(element), list):
    523         raise ValueError(
    524             "The `formatting_func` should return a list of processed strings since it can lead to silent bugs."
    525         )

File ~/miniconda3/envs/stable_env/lib/python3.9/site-packages/datasets/formatting/formatting.py:277, in LazyDict.__getitem__(self, key)
    276 def __getitem__(self, key):
--> 277     value = self.data[key]
    278     if key in self.keys_to_format:
    279         value = self.format(key)

KeyError: 'text'

Any leads will be appreciated.

**Comment by beingdutta** [comment]
Need trl version 0.12.0

**Comment by mit1208** [comment]
sorry I couldn't get back to you because of holidays. Glad you figured out.

**Comment by mit1280** [comment]
sorry I couldn't get back to you because of holidays. Glad you figured out.
